### ISSUE TITLE
incomplete parsing of gene-gene edge provenance from semmedgene

### ISSUE THREAD

**Issue by andrewsu** [kevinxin90/bte_schema#5] opened 2019-09-17 04:54 UTC
This is a code snippet to get gene-gene edges from https://pending.biothings.io/semmedgene:

```
gene = "57506"
seqd = SingleEdgeQueryDispatcher(input_cls="Gene",
                                input_id="bts:entrez",
                                values=gene,
                                output_cls="Gene",
                                output_id="bts:entrez",
                                registry=reg)
seqd.query()
seqd.display_edge_info("57506","3661")
```

which returns this object:

```
{0: {'info': {'@type': 'Gene',
   'bts:umls': ['C1334139'],
   '$source': 'semmedgene'},
  'label': 'bts:molecularlyInteractsWith',
  'source': 'semmedgene'}}
```
But the corresponding semmedgene result has more info about the specific PMIDs. From https://pending.biothings.io/semmedgene/gene/C1864770, this is the snippet that corresponds to the BTE result above:
```
"interacts_with": {
    "gene": [
        {
            "pmid": [
                "25636800",
                "20161788"
            ],
            "umls": "C1334139"
        },
```
This issue does not appear to affect gene-chemical queries through BTE.

**Comment by kevinxin90** [comment] 2019-09-18 21:53
The problem is caused when merging equivalent nodes with different identifiers.

It's fixed now. Feel free to try again. Just need to reinstall the python package.

Fixed in commit: c950be26cca8737b49a1e99bd3d2bc6b1d6bb8d8

**Closed by kevinxin90** 2019-09-18 21:53 UTC
